name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Staging
        uses: Techie-Pi/node-vps-deployment@main
        with:
          remote-path: "~/applitations/deploy/"
          host: ${{ secrets.HOST }}
          username: "cargo"
          port: 22
          password: ${{ secrets.SSH_KEY }}
          pm2-id: "staging"