name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Deploy App
        uses: azurydev/deploy-action@v0
        with:
          host: "72.167.41.179"
          username: "cargo"
          privateKey: "Cg5580*7gs@"
          destination: /cargo/applications
          dependencies: true # update remote package.json, package-lock.json, and dependencies
          pm2: 0 # pm2 process name or id