name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Deploy App
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: chrisjsimpson/deploy-wireguard-algo-vpn-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
            public-ip: ${{ secrets.HOST }}